# Generated by Django 4.1.3 on 2022-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itname', models.CharField(max_length=25)),
                ('itno', models.IntegerField()),
                ('itprice', models.IntegerField()),
                ('itqty', models.IntegerField()),
            ],
        ),
    ]
